### ISSUE TITLE
Can't start kafka-monitor

### ISSUE THREAD

**Issue by ljianchao** [linkedin/kafka-monitor#10]
While I start KafkaMonitor to run tests/services specified in the config file, it shown this info:

> : command not found-start.sh: line 9: 
: command not found-start.sh: line 11: 
: command not found-start.sh: line 13: 
 (No such file or directory)ava.io.FileNotFoundException: config/kafka-monitor.properties
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at com.linkedin.kmf.core.KafkaMonitor.main(KafkaMonitor.java:118)

but the file of kafka-monitor.properties is exist, and the path is correct.
Please help me sovle the problem.
Thanks.

**Comment by ljianchao** [comment]
When I debug the code, I find the parameter of com.linkedin.kmf.core.KafkaMonitor.main(KafkaMonitor.java:118) is endwith "\r", like this:

> "config/kafka-monitor.properties\r"

Why is that?

**Comment by lindong28** [comment]
@ljianchao Did you run `./bin/kafka-monitor-start.sh config/kafka-monitor.properties`? Which operating system did you use? Is it Windows?

KafkaMonitor.java:118 is `try (BufferedReader br = new BufferedReader(new FileReader(args[0]))) {`, which doesn't include `\r`. Where did you see `\r`

Can you try replace that line with 

`try (BufferedReader br = new BufferedReader(new FileReader(args[0].trim()))) {`

**Comment by ljianchao** [comment]
My operating system is fedora and replace the line is ok.

**Comment by lindong28** [comment]
Cool. I just submitted a patch to fix it.
