### ISSUE TITLE
Produce more than ~1000 records per second?

### ISSUE THREAD

**Issue by rjharvey** [linkedin/kafka-monitor#100]
Hi,

I am trying to test what throughput I can expect with my currently available hardware and configured numbers of brokers / partitions / replication factor, etc.

However, using this monitor, it seems like I can only lower "produce.record.delay.ms" to 1, which obviously means the most that I am able to produce/consume is 1000 records / second.

Is there any way of improving this?  I tried changing the value of "produce.record.delay.ms" to 0, and the entire thing stops working (all values 0.0).  Can I spin up one more than one producer, for example?

Thank you for your help.

**Comment by lindong28** [comment]
@rjharvey kafka-monitor is intended to be used for monitoring availability and functionality of the kafka service, and therefore should not need to send more than 1000 messages a second.

If you want to stress test the maximum throughput of your kafka cluster, kafka-monitor is probably not the right tool for you even if `produce.record.delay.ms` can be set to 0. Can you try using bin/kafka-producer-perf-test.sh in the Apache Kafka's repository to stress test your cluster?

**Comment by rjharvey** [comment]
@lindong28 Ok, thank you very much.
