### ISSUE TITLE
ERROR : org.apache.kafka.common.errors.InvalidPartitionsException: number of partitions must be larger than 0

### ISSUE THREAD

**Issue by waewoo** [linkedin/kafka-monitor#104]
Hello, 

When i run single-cluster-monitor.sh, i have the following error...

What can explain this error ?

For information, i use apache 1.0 version.

thanks

[2017-12-27 09:36:49,157] INFO Session: 0x1607f0c633100a4 closed (org.apache.zookeeper.ZooKeeper)
[2017-12-27 09:36:49,158] ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
org.apache.kafka.common.errors.InvalidPartitionsException: number of partitions must be larger than 0

**Comment by lindong28** [comment]
@waewoo Sorry for late reply. LinkedIn had a week-long holiday last week. Do you have the complete stack trace that shows where this `InvalidPartitionsException` comes from?

Can you try to run kafka-topics.sh (available in the Apache Kafka) on the same host where you run single-cluster-monitor.sh, to describe an existing topic in your cluster? I just want to double check that the kafka-topics.sh can successfully access the zookeeper from this host. Thanks.

**Comment by lindong28** [comment]
@waewoo Sorry for late reply. LinkedIn had a week-long holiday last week.

Can you tell me the zookeeper path provided to the `single-cluster-monitor.sh`? Also, what is the value of `zookeeper.connect` in your broker configuration?
