### ISSUE TITLE
records-produced-rate not increasing on increasing number of brokers

### ISSUE THREAD

**Issue by sidSingla** [linkedin/kafka-monitor#108]
With single broker in the cluster, I am seeing records-produced-rate to be approx ~137.
I modified kafka-monitor.properties config file and added one more broker in bootstrap.servers.
I am expecting the records-produced-rate to increase because of messages flowing on 2 brokers now, but the rate is same. Tried this with seven brokers as well.
Is this an expected behaviour or is there something wrong with my configurations.
Rest of the configuration is default only.

"zookeeper.connect": "zk1:2181,zk2:2181",
"bootstrap.servers": "broker1:9092,broker2:9092",

**Comment by lindong28** [comment]
@sidSingla Did you add just one more broker in the config, or did you add one more broker to the cluster? The definition of `bootstrap.servers` can be found in https://kafka.apache.org/documentation/#configuration. It says that "The client will make use of all servers irrespective of which servers are specified here for bootstrapping—this list only impacts the initial hosts used to discover the full set of servers".

**Comment by sidSingla** [comment]
@lindong28 I added broker in the config. It is already present in the cluster. So, are all the kafka cluster brokers discovered with the help of zookeeper ?
Sorry but I am not able to get the definition of bootstrap.servers completely.

**Comment by lindong28** [comment]
@sidSingla Sorry for late reply. Yes, all the brokers in the cluster will be discovered using zookeeper. They don't have to show up in the bootstrap.servers.

**Comment by sidSingla** [comment]
@lindong28 Thanks for the explanation. Got it completely 👍
