### ISSUE TITLE
Make Jolokia port/url configurable ( in JolokiaService and in webapp/index.html )

### ISSUE THREAD

**Issue by andlaz** [linkedin/kafka-monitor#113]
Hi,

i had a requirement to deploy kafka-monitor in kubernetes, and expose JettyService ( specifically, the small js ui that draws a couple graphs ) and JolokiaService over an ingress.

In the current master branch this is rather difficult because index.html hardcodes the jolokia port/url as http:// + location.host.split(':')[0] + :8778/jolokia , with the port also hardcoded in JolokiaService.

I will be sending a PR for your review to discuss/potentially fix these issues.

thanks!
Andras

**Comment by andrewchoi5** [comment]
Hi Andlaz, it seems as though there already is a `Pull Request` that is ongoing and in progress, Thus, could I close this issue? Thanks! 😄
