### ISSUE TITLE
Can i monitor the latency in topics ?

### ISSUE THREAD

**Issue by keyankay** [linkedin/kafka-monitor#115]
Hi,
I am a newbie to this, wanted to check if there is a way if i could see the latency in a topic without producing or consuming using the Producer Service or Consumer Service i.e i want to monitor a topic with real messages flowing and not the ones generated from the Producer Service or the Consumer Service.

**Comment by lindong28** [comment]
Hey @keyankay, kafka-monitor by its design does not provide a way to monitor latency of existing topic.
