### ISSUE TITLE
all values 0.0

### ISSUE THREAD

**Issue by anandsk123** [linkedin/kafka-monitor#12]
I am able to get the monitor running locally in my laptop against a Kafka cluster by changing only the "topic" and "zookeeper.connect"

but when I run the monitor with the same config on a remote box it does not produce and send any msgs, please help with this.

**Comment by lindong28** [comment]
@anandsk123 Did you provide the right bootstrap.servers? Are you able to telnet from that remote host to the host:port of both zookeeper and brokers? Is there other Kafka Monitor instance producing to the same topic? Can you try again after removing jetty-service and jolokia-service from kafka-monitor.properties?

**Comment by anandsk123** [comment]
FYI, I have still not got it to work.
What exactly does bootstrap.servers does?
Does this monitor itself creates and produces msgs to the queue?

**Comment by anandsk123** [comment]
Hi Dong Lin, 

Can you give me the 0.8 version of 
build.gradle:24:    compile 'org.apache.kafka:kafka_2.11:0.9.0.1'
build.gradle:25:    compile 'org.apache.kafka:kafka-clients:0.9.0.1'

please, this could potentially solve the problem. Seems to be version compatibility issue.
The kafka cluster I am trying to monitor is 0.8.2.1
here is the error/issue I am seeing in the logs: https://issues.apache.org/jira/browse/KAFKA-2750

I wonder why this issue is only happening in remote box and not my local box

Anand

**Comment by lindong28** [comment]
@anandsk123 You can use branch 0.8.2.2 to monitor 0.8 Kafka cluster. Explanation of `bootstrap.servers` can be found at http://kafka.apache.org/documentation.html#producerconfigs.

**Comment by lindong28** [comment]
@anandsk123 And yes, the monitor itself produces messages to the queue. Therefore you should create a topic that used only by a Kafka Monitor instance.
