### ISSUE TITLE
No branch support kafka version 1.0.1

### ISSUE THREAD

**Issue by wenchangwu** [linkedin/kafka-monitor#121]
now no branch support kafka version 1.0.1

**Comment by lindong28** [comment]
Yeah we should definitely support Kafka 1.0. Currently LinkedIn is still using Kafka 0.11 and that is why we have not upgraded kafka-monitor to use 0.11. I will create a branch later to support 1.0.

**Comment by lindong28** [comment]
Sorry for the delay @wenchangwu. It is long over due. I just created PR https://github.com/linkedin/kafka-monitor/pull/127 to address the issue.

**Comment by lindong28** [comment]
@wenchangwu Sorry for the delay.. the latest branch is using kafka 1.1.1 now.
