### ISSUE TITLE
Is there a plan to support latest release of Kafka 0.10.0?

### ISSUE THREAD

**Issue by kirancse507** [linkedin/kafka-monitor#13]
Hi,

Is there a plan to support latest release of Kafka 0.10.0?

Thanks,
Kiran

**Comment by lindong28** [comment]
@kirancse507 Of course. Kafka Monitor is used at LinkedIn to monitor production clusters. It needs to support 0.10.* when LinkedIn upgrades Kafka Cluster to 0.10.*
