### ISSUE TITLE
Kafka Monitor GUI, metrics table != metrics figure

### ISSUE THREAD

**Issue by fvigotti** [linkedin/kafka-monitor#136]
I have this table 
```

Metric Name | Value
-- | --
produce-availability-avg | 1
records-produced-rate | 147.77551225055987
records-lost-rate | 0
records-duplicated-rate | 0
records-delay-ms-avg | 2.2268534335497097
records-delay-ms-99th | 4.998000799680128
records-delay-ms-999th | 5.997600959616154
records-delay-ms-max | 84

```

but metrics figure shows about 2 ( with a total of 1400 )  `records-lost-rate `

**Comment by lindong28** [comment]
@fvigotti Sorry, the web GUI is only used for demo and we don't really use or support this in production at LinkedIn. So if there is non-trivial issue with GUI we don't plan to debug it.

kafka-monitor provides a way to expose jmx-metrics. LinkedIn uses inGraph (see https://engineering.linkedin.com/blog/2017/08/ingraphs--monitoring-and-unexpected-artwork) to monitor jmx metrics. There are a bunch of open source libraries and service to monitor jmx metrics, e.g. https://graphiteapp.org/.
