### ISSUE TITLE
[Question] multi cluster test - app with only a consumer service

### ISSUE THREAD

**Issue by d1egoaz** [linkedin/kafka-monitor#139]
I'd like to run a kafka-monitor only consumer instance in a multi cluster environment.

According to the docs this might be possible:
https://github.com/linkedin/kafka-monitor/wiki/Design-Overview
<img src="https://screenshot.click/2018-10-22_10-18-21_o4q1g.png" width="50%" />

but after reading the code, it seems there is no `apps` that supports above scenario, as the ones provided in the repo needs the following `services`: partitioner, producer, and a consumer.
https://github.com/linkedin/kafka-monitor/blob/5dc6395e4882240ce12623e27f612cfaa0990896/src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java#L49-L51

So, I just want to double check this before start creating an `app` that only reads a consumer config.
Similar to `SingleClusterMonitor` but reading only the consumer configuration.

Would that be enough to have a kafka-monitor consumer instance?

And thanks for this amazing tool! 🍻

**Comment by lindong28** [comment]
Hey @d1egoaz, yes you can do it by adding the following example text in kafka-monitor.properties :)

```
  "consume-service": {
    "class.name": "com.linkedin.kmf.services.ConsumeService",
    "topic": "kafka-monitor-topic",
    "zookeeper.connect": "localhost:2181",
    "bootstrap.servers": "localhost:9092",
    "produce.record.delay.ms": 100,
    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {

    }
  }
```

**Comment by d1egoaz** [comment]
That makes sense @lindong28 , I thought the entry point had to be an `app`
thanks!

**Comment by jyates** [comment]
Just bumped into this too. Would be helpful if there was a good way to add this to the documentation.. maybe an example in the Service Overview part of the wiki?

**Comment by smccauliff** [comment]
Is more explanation needed?  https://github.com/linkedin/kafka-monitor/wiki/App-Configuration

**Comment by jyates** [comment]
Beautiful. thanks Sean!
