### ISSUE TITLE
Configure records produced per second

### ISSUE THREAD

**Issue by anandsk123** [linkedin/kafka-monitor#15]
How do I configure records produced per second by the monitor? It is pretty high right now. 
Also I don't want to produce every second. How do I configure this as well?

**Comment by lindong28** [comment]
@anandsk123 You can modify produce.record.delay.ms in the config/kafka-monitor.properties to specify the delay in ms before Kafka Monitor sends the next message. You can use this config to control the number of messages that will be sent in each second.

**Comment by anandsk123** [comment]
I tried changing this, and also rebuilding the project. It does not throttle.
Please let me know.

**Comment by lindong28** [comment]
@anandsk123 I have tested Kafka Monitor by tuning `produce.record.delay.ms` in config/kafka-monitor.properties. The records-produced-total increases at a lower rate as expected if I increase `produce.record.delay.ms`. How do you figure out this is not working? Have you asked others to reproduce the issue?

**Comment by anandsk123** [comment]
How do I configure 'records-produced-rate' specifically?
