### ISSUE TITLE
StatsdReportService throws array out of bounds exception

### ISSUE THREAD

**Issue by DefSol** [linkedin/kafka-monitor#150]
When enabling the example statsd configuration block, the statsdReporter throws above exception in the `generateStatsdMetricName` method.

In my investigation, it would appear that the line 91 of the  `StatsdMetricsReporterService` class fails for the 
 metric `"kmf:type=kafka-monitor:offline-runnable-count"` This metric name varies from all other metric names, and hence where I suspect the exception occurs.

I'm just trying to understand if this was by design, i.e. the `kmf:type=kafka-monitor:offline-runnable-count` was never intended to be passed via statsd, or just an oversight on the implementation?

I would also like to confirm what that metric (`kmf:type=kafka-monitor:offline-runnable-count`) represents.

For now if I do not include the metric name in the configuration block, I can pass all other metrics to my statsd listener.

I did spend some time to see if this issue had been logged previously, but could not find anything. Happy to help out where I can.

**Comment by smccauliff** [comment]
Sorry we are slow to open source user requests on this software.  Does this still trouble you?  If so can you paste the stack trace here.

**Comment by andrewchoi5** [comment]
@DefSol Hi, is this still an active issue?

**Comment by DefSol** [comment]
Hey @andrewchoi5 sorry for the slow reply. I am no longer working with this project, so it is harder to confirm. Let's close the issue for now and if I get some time too look at it I'll provide better artifacts. Also thanks for what you do, this is a great project
