### ISSUE TITLE
Connect to secure Kafka

### ISSUE THREAD

**Issue by Sparker0i** [linkedin/kafka-monitor#155]
I have a secured Kafka system present which I would like to monitor using this tool. How do I make changes in the config file in order to connect to a secured Kafka system.

I put the following K-V pairs in a Properties object in my Java code while connecting to my secured Kafka system:
security.protocol -> SASL_SSL
sasl.mechanism -> PLAIN
sasl.jaas.config -> org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password"
ssl.protocol -> TLSv1.2
ssl.enabled.protocols -> TLSv1.2
ssl.endpoint.identification.algorithm -> HTTPS

**Comment by smccauliff** [comment]
There are sections in the config:
```json
"produce.producer.props": {
      "client.id": "kmf-client-id"
    },

and 

 "consume.consumer.props": {

}
```

Where you can add arbitrary properties to pass the the Kafka client instances.

**Comment by andrewchoi5** [comment]
@Sparker0i The changes you need can be _specified_ in the **config** file. Is it safe to close this particular issue? Thanks!
