### ISSUE TITLE
[2019-07-16 02:08:52,438] ERROR App multi-cluster-monitor is not fully running. (com.linkedin.kmf.KafkaMonitor)

### ISSUE THREAD

**Issue by chenlianggu** [linkedin/kafka-monitor#157]
./bin/kafka-monitor-start.sh config/multi-cluster-monitor.properties

#running in foreground give me below errors:

 (com.linkedin.kmf.services.DefaultMetricsReporterService)
**[2019-07-16 02:08:47,437] ERROR App multi-cluster-monitor is not fully running. (com.linkedin.kmf.KafkaMonitor)**
[2019-07-16 02:08:47,441] INFO kmf.services:name=multi-cluster-monitor,type=produce-service:produce-availability-avg=NaN
kmf.services:name=multi-cluster-monitor,type=consume-service:consume-availability-avg=0.0
kmf.services:name=multi-cluster-monitor,type=produce-service:records-produced-total=0.0
kmf.services:name=multi-cluster-monitor,type=consume-service:records-consumed-total=0.0
kmf.services:name=multi-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=multi-cluster-monitor,type=consume-service:records-duplicated-total=0.0
kmf.services:name=multi-cluster-monitor,type=consume-service:records-delay-ms-avg=0.0
kmf.services:name=multi-cluster-monitor,type=produce-service:records-produced-rate=0.0
kmf.services:name=multi-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=multi-cluster-monitor,type=consume-service:consume-error-rate=0.0
and repeats............

config file output:
cat ~/kafka-monitor/config/multi-cluster-monitor.properties
{
    "multi-cluster-monitor": {
        "class.name": "com.linkedin.kmf.apps.MultiClusterMonitor",
        "topic": "kafka-monitor-topic",

        "produce.service.props": {
            "zookeeper.connect": "192.168.33.101:2181/first-cluster",
            "bootstrap.servers": "192.168.33.101:9092",
            "produce.record.delay.ms": 100,
            "produce.producer.props": {
                "client.id": "kafka-monitor-client-id"
            }
        },

        "consume.service.props": {
            "zookeeper.connect": "192.168.33.102:2181/last-cluster",
            "bootstrap.servers": "192.168.33.102:9092",
            "consume.latency.sla.ms": "20000",
            "consume.consumer.props": {
                "group.id": "kafka-monitor-group-id"
            }
        },

        "topic.management.props.per.cluster": {
            "first-cluster": {
                "zookeeper.connect": "192.168.33.101:2181/first-cluster",
                "topic-management.topicCreationEnabled": true,
                "topic-management.replicationFactor": 1,
                "topic-management.partitionsToBrokersRatio": 2.0,
                "topic-management.rebalance.interval.ms": 600000,
                "topic-management.topicFactory.props": {}
            },

            "last-cluster": {
                "zookeeper.connect": "192.168.33.102:2181/last-cluster",
                "topic-management.topicCreationEnabled": true,
                "topic-management.replicationFactor": 1,
                "topic-management.partitionsToBrokersRatio": 2.0,
                "topic-management.rebalance.interval.ms": 600000,
                "topic-management.topicFactory.props": {}
            }
        }

    },
.............................

**Comment by smccauliff** [comment]
The boostrap server list is identical for first cluster and last cluster.  Should it be?

**Comment by chenlianggu** [comment]
> The boostrap server list is identical for first cluster and last cluster. Should it be?

Hi Sean,
it's different ip address.

**Comment by smccauliff** [comment]
Ah.  101 vs 102.

Are you mirroring messages between the two clusters?

**Comment by chenlianggu** [comment]
ye, it's a super simple setup, two clusters with 1 zk, and 1 kafka each.
mirror making has been setup and it's working.
all ports and communications are verified working.

also ran a single cluster monitoring and it's working. messaged produced to kafka-monitor-topic on cluster A is also being replicated to cluster B via mirror making with * white list.

just this multi cluster monitoring is giving me really hard time.

**Comment by chenlianggu** [comment]
okay, i just made it working.
it's to do with the zk namespace....my setup was under /.
it would be better if error message could be more specific.

**Comment by smccauliff** [comment]
It has no way of knowing if the zk node that was chosen was bad.

**Comment by mrvindu** [comment]
i am doing single-cluster monitor, but getting similar error message.
how did you fix this, can you post the syntax please ?

**Comment by snneha22** [comment]
Hey, i am trying to run ./bin/kafka-monitor-start.sh config/multi-cluster-monitor.properties.
Changed conf file accordingly to include xk and bootstrap servers, getting same error.
Could you help to fix to issue
