### ISSUE TITLE
Unable to download kafka manager 2.0

### ISSUE THREAD

**Issue by ssg1205** [linkedin/kafka-monitor#158]
I am getting the below error when i run  `./sbt clean dist`  -->

`error] sbt.librarymanagement.ResolveException: unresolved dependency: org.foundweekends#bintry_2.12;0.5.2: Resolution failed several times for dependency: org.foundweekends#bintry_2.12;0.5.2 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends/bintry_2.12/0.5.2/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends/bintry_2.12/0.5.2/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends/bintry_2.12/0.5.2/jars/bintry_2.12.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends/bintry_2.12/0.5.2/jars/bintry_2.12.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends/bintry_2.12/0.5.2/jars/bintry_2.12.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.foundweekends#bintry_2.12;0.5.2: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends/bintry_2.12/0.5.2/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] `

I have checked my Java version. It is 1.8 -->

`$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)`

Can you please help me with this issue?

**Comment by smccauliff** [comment]
Your log says: "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target [error] "

You are having some kind of SSL issues when connecting to bintray
