### ISSUE TITLE
multiple topic

### ISSUE THREAD

**Issue by dlrudwns135** [linkedin/kafka-monitor#164]
how to monitor multiple topic?
and would you tell me list of monitor prop

**Comment by andrewchoi5** [comment]
안녕하세요 이경준님, 질문 감사합니다.
현재 카프카 모니터에는 다수의 토픽을 사용하는 `멀티클러스터모니터` 어플리케이션이 장착되어 있습니다. 소스코드안에 들어가보시면 아래와 같이 클래스위에 설명이 첨부돼 있습니다. 즉, 멀티클러스터모니터는 `멀티클러스터토픽매니지먼트서비스`를 사용해 **복수의** 클러스터의 복수의 모니터링 **토픽들을** 관리할 수 있는 기능을 갖고 있습니다. 카프나 모니터 프로퍼티들은 `kafka-monitor.properties`혹은 `multi-cluster-monitor.properties` 안에 정의돼있습니다. 사용하시는 프로그램안에 카프카 모니터를 dependency로 갖고 있을경우 코드 프로퍼티 파일안에 예시처럼 세팅들을 구성하시면 됩니다. 

Hello Mr Kyun Jun Lee, thanks for the question. Currently, Kafka Monitor is capable of producing to and consuming from multiple topics if you are using the `MultiClusterMonitor` application in Kafka Monitor. And this is achieved by using the **MultiClusterTopicManagementService** to manage the monitor topics across Kafka clusters and make sure they have the same number of partitions.


```
{
  "multi-cluster-monitor": {
    "class.name": "com.linkedin.kmf.apps.MultiClusterMonitor",
    "topic": "kafka-monitor-topic",
    "produce.service.props": {
      "zookeeper.connect": "localhost:2181/first_cluster",
      "bootstrap.servers": "localhost:9092",
      "produce.record.delay.ms": 100,
      "produce.producer.props": {
        "client.id": "kafka-monitor-client-id"
      }
    },
    "consume.service.props": {
      "zookeeper.connect": "localhost:2181/last_cluster",
      "bootstrap.servers": "localhost:9095",
      "consume.latency.sla.ms": "20000",
      "consume.consumer.props": {
        "group.id": "kafka-monitor-group-id"
      }
    },

    "topic.management.props.per.cluster" : {
      "first-cluster" : {
        "bootstrap.servers": "localhost:9092",
        "zookeeper.connect": "localhost:2181/first_cluster",
        "topic-management.topicCreationEnabled": true,
        "topic-management.replicationFactor" : 1,
        "topic-management.partitionsToBrokersRatio" : 2.0,
        "topic-management.rebalance.interval.ms" : 600000,
        "topic-management.topicFactory.props": {
        }
      },

      "last-cluster" : {
        "bootstrap.servers": "localhost:9095",
        "zookeeper.connect": "localhost:2181/last_cluster",
        "topic-management.topicCreationEnabled": true,
        "topic-management.replicationFactor" : 1,
        "topic-management.partitionsToBrokersRatio" : 2.0,
        "topic-management.rebalance.interval.ms" : 600000,
        "topic-management.topicFactory.props": {
        }
      }
    }

  },
...

```
> The MultiClusterMonitor app is intended to monitor the performance and availability of a pipeline of one or more Kafka clusters. It creates one producer and one consumer with the given configuration, produces messages with increasing
> * integer in the message payload, consumes messages, and keeps track of the number of lost messages, duplicate messages, end-to-end
> * latency etc. Furthermore, MultiClusterMonitor use MultiClusterTopicManagementService to manage the monitor topics
> * across Kafka clusters and make sure they have the same number of partitions.

**Comment by dlrudwns135** [comment]
네 알고 있습니다. 
그러나 제가 알고싶은건 multitopic을 모니터링 할때 설정파일에 어떻게 작성하냐 입니다.

Yes. I know.
However, what i want know is how to write config for multitopic monitoring.

**Comment by smccauliff** [comment]
Why do you want to have multiple topics?  How is this beneficial?

**Comment by andrewchoi5** [comment]
> 네 알고 있습니다.
> 그러나 제가 알고싶은건 multitopic을 모니터링 할때 설정파일에 어떻게 작성하냐 입니다.
> 
> Yes. I know.
> However, what i want know is how to write config for multitopic monitoring.

If you are interested in knowing how to configure topics for the multi-cluster monitoring, you would need to make modifications to the `multi-cluster-monitor.properties` file in a way that changes the values for the following fields:
- The ZooKeeper link for the ZooKeeper server that you have already running for the producer instance.
- The Bootstrap Server link for the ZooKeeper server that you have already running for the consumer instance.
- Your cluster(s)'s bootstrap servers address 
- Your cluster(s)'s zookeeper connect address
- and other topic-management properties as it suits your needs 

```"topic.management.props.per.cluster" : {
      "first-cluster" : {
        "bootstrap.servers": "localhost:9092",
        "zookeeper.connect": "localhost:2181/first_cluster",
        "topic-management.topicCreationEnabled": true,
        "topic-management.replicationFactor" : 1,
        "topic-management.partitionsToBrokersRatio" : 2.0,
        "topic-management.rebalance.interval.ms" : 600000,
        "topic-management.topicFactory.props": {
        }
      },

      "last-cluster" : {
        "bootstrap.servers": "localhost:9095",
        "zookeeper.connect": "localhost:2181/last_cluster",
        "topic-management.topicCreationEnabled": true,
        "topic-management.replicationFactor" : 1,
        "topic-management.partitionsToBrokersRatio" : 2.0,
        "topic-management.rebalance.interval.ms" : 600000,
        "topic-management.topicFactory.props": {
        }
      }
    }
```
