### ISSUE TITLE
Remove zookeeper dependency

### ISSUE THREAD

**Issue by jmcristobal** [linkedin/kafka-monitor#165]
Hi

First and foremost, congratulations for this tool. It's great being able to measure these metrics on kafka from a client side.
This issue is in fact a question. Do you plan to remove the dependency with zookeeper? some of our clusters run on AWS and zookeeper is not accessible so I can't use kafka-monitor to conduct this kind of end-to-end testing. I've followed the implementation and I think kafka admin API covers most of the things we get from zookeeper. Moreover, once KIP-500 is merged, zookeeper will be gone.

Maybe there is some way to not use zookeeper in the current version, but I have not found it.

Best regards.

**Comment by andrewchoi5** [comment]
Hi @jmcristobal the concern raised in this particular issue is in progress and ongoing. Thanks for bringing it up.

**Comment by waewoo** [comment]
Hello, 

Have you got some news about implementation of this feature ?

Thanks

**Comment by zigarn** [comment]
@waewoo: looks like PR #175 did it.

**Comment by zigarn** [comment]
> @waewoo: looks like PR #175 did it.

But https://github.com/linkedin/kafka-monitor/blob/c42ea7debc15ed2e6e3847eb17b15ec23e00708a/src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java#L408 still depends on Zookeeper.
