### ISSUE TITLE
Broken ConsumeService on latest release

### ISSUE THREAD

**Issue by d1egoaz** [linkedin/kafka-monitor#195]
According to this: https://github.com/linkedin/kafka-monitor/issues/139
and this: https://github.com/linkedin/kafka-monitor/wiki/App-Configuration

We could have something like this configured:
```json
"consume-service": {
    "class.name": "com.linkedin.kmf.services.ConsumeService",
    "topic": "kafka-monitor-topic",
    "zookeeper.connect": "localhost:2181",
    "bootstrap.servers": "localhost:9092",
    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
    }
```

However, this commit change the method's arguments on `ConsumeService`
https://github.com/linkedin/kafka-monitor/commit/f1a21c9a16df1d274f424111ae0fab69e6f85d0b
![image](https://user-images.githubusercontent.com/950087/72084896-58a5c000-32d2-11ea-9575-eb41d86040eb.png)

and now it's failing with:
```
Exception in thread "main" java.lang.NoSuchMethodException: com.linkedin.kmf.services.ConsumeService.<init>(java.util.Map, java.lang.String)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:71)
        at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:166)
```
as the executor is only sending 2 arguments, instead of the 3 the method is now expecting.

**Comment by andrewchoi5** [comment]
there is a PR that's ready to be released regarding the constructor parameters for new KMF. thanks.

**Comment by andrewchoi5** [comment]
Hello,

Could you please include the full stacktrace as well as the command you've actually executed to produce this?

**Comment by andrewchoi5** [comment]
A Pull Request will be ready to resolve this NoSuchMethodException issue for ConsumeService. Thanks.

**Comment by andrewchoi5** [comment]
`https://github.com/linkedin/kafka-monitor/pull/196`

**Comment by d1egoaz** [comment]
Great 👍 thank you !

**Comment by andrewchoi5** [comment]
No problem! Thank you 👍
