### ISSUE TITLE
Monitor custom metrics

### ISSUE THREAD

**Issue by panda87** [linkedin/kafka-monitor#21]
Hi

I'm using kafka 0.8.2.1 and I'm trying to add additional metrics to the index.html + config lists.
I can see that the UI show the expected metrics but in the logs I dont see the lines as well as the default metrics, does this project support that?

Thanks
D.

**Comment by lindong28** [comment]
@panda87 If you update report.metrics.list  in https://github.com/linkedin/kafka-monitor/blob/master/config/kafka-monitor.properties and start Kafka-Monitor using `./bin/kafka-monitor-start.sh config/kafka-monitor.properties`, you should see metrics value in the console, no?

**Comment by panda87** [comment]
I tried but I don't see anything in the console log.
Do you have metrics name that I can test with?

**Comment by lindong28** [comment]
@panda87 Can you provide instructions to reproduce this, i.e. the link to your clone of the repository that includes your change to the config file, and the comments you used to start Kafka-Monitor and so on.
