### ISSUE TITLE
Bintray repository not available

### ISSUE THREAD

**Issue by zigarn** [linkedin/kafka-monitor#216]
https://bintray.com/search?query=kafka-monitor leads to https://bintray.com/linkedin/maven/kafka-monitor which is 404.

https://dl.bintray.com/linkedin/maven/com/linkedin/kmf/kafka-monitor/2.0.8/ then get a '403 Forbidden' when trying to download [kafka-monitor-2.0.8.tar.gz](https://dl.bintray.com/linkedin/maven/com/linkedin/kmf/kafka-monitor/2.0.8/kafka-monitor-2.0.8.tar.gz)

BTW, would be nice to have tarball and zip of builded artifact in the releases assets.

**Comment by zigarn** [comment]
Looks like it's fixed now.

**Comment by smccauliff** [comment]
Someone forgot to pay for the Linkedin bintray account.
