### ISSUE TITLE
Question about the localhost:8000/index.html

### ISSUE THREAD

**Issue by msgPDC** [linkedin/kafka-monitor#226]
Question about Get metric values (e.g. service availability, message loss rate) in real-time as time series graphs. Does this feature still work.

Where is the port for the web app configured now that it has been removed from the kafka-monitor.properties. I cannot hit localhost:8000/index.html successfully (the site can't be reached)

**Comment by lucasGras** [comment]
+1

**Comment by andrewchoi5** [comment]
Hi msgPDC, we previously removed some unnecessary dependencies on [Jetty](https://github.com/linkedin/kafka-monitor/commit/fcb8b27e40b7f5ab77254c54ca5ee33d81b816f9). which is needed only for Jolokia Service, to narrow down the scope of the testng dependency..
It will initiate the embedded web server if you wanted to run the service.

+1 @smccauliff if he wants to add any extra insights.

**Comment by kenttanl** [comment]
index.html is just a static page, I think you can put the related static resources into a web server and then open it. I adjusted the position of `/js /..` to `./js/..` and quickly opened it via IDEA.
![image](https://user-images.githubusercontent.com/15412193/80090202-ba441e80-8591-11ea-9735-df61fd1d1ed3.png)
