### ISSUE TITLE
can't access grap

### ISSUE THREAD

**Issue by letran3691** [linkedin/kafka-monitor#282]
I had start **./bin/kafka-monitor-start.sh config/kafka-monitor.properties** and can using 
curl localhost:8778/jolokia/read/kmf.services:type=produce-service,name=*/produce-availability-avg
{"request":{"mbean":"kmf.services:name=*,type=produce-service","attribute":"produce-availability-avg","type":"read"},"value":{"kmf.services:name=single-cluster-monitor,type=produce-service":{"produce-availability-avg":1.0}},"timestamp":1592473146,"status":200}.

but can't access to graphic. I'm checked port 8000 it's not exist

![image](https://user-images.githubusercontent.com/19284401/85005387-eb506200-b182-11ea-80e6-bc7a5ea9a776.png)

plz help me. thanks

**Comment by andrewchoi5** [comment]
Hello @letran3691 -- please review https://github.com/linkedin/kafka-monitor/pull/269.

**Comment by letran3691** [comment]
> Hello @letran3691 -- please review #269.
 thanks you have reply.
I had config with https://github.com/linkedin/kafka-monitor/pull/269/files/8bb07357ee0a5a5190bbab37bc47708567cb5a0f
after compile ./gradlew jar then output error  "not override abstract method awaitShutdown(long,TimeUnit) in Service" 

![image](https://user-images.githubusercontent.com/19284401/85091234-36b15180-b211-11ea-9b6c-dd3a4d11d4bf.png)

I don't know more code. Below is files I had edit and create before compile. You can see help me plz. Thanks!

build.gradle
https://paste.ofcode.org/VpEVpXrhmxxHE2gBF9kSjj

 config/xinfra-monitor.properties
https://paste.ofcode.org/Z2rciSWNexBJnDzAN5RgKE

 src/main/java/com/linkedin/kmf/services/JettyService.java 
https://paste.ofcode.org/iymrvGAatRiHPdfetXMnnw

 src/main/java/com/linkedin/kmf/services/JettyServiceFactory.java
https://paste.ofcode.org/wDbNn6msGX6QQw2SVFBcSb

src/main/java/com/linkedin/kmf/services/JolokiaService.java
https://paste.ofcode.org/eK82WE2X3wqhZVRnsfNiiG

**Comment by andrewchoi5** [comment]
Thanks for the files and screenshot.
I have made the changes in that branch (PR) and have conducted some merge conflict resolutions.

Please try again on the clean copy of that branch once again.
On my end I see:
```
 ~/kafka-monitor   andchoi_ultimateSoftwareInquiries ?  ./gradlew jar                                                                                                                                 SIGINT(2) ↵  10851  22:22:05

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by letran3691** [comment]
> Thanks for the files and screenshot.
> I have made the changes in that branch (PR) and have conducted some merge conflict resolutions.
> 
> Please try again on the clean copy of that branch once again.
> On my end I see:
> 
> ```
>  ~/kafka-monitor  andchoi_ultimateSoftwareInquiries ? ./gradlew jar
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD SUCCESSFUL in 1s
> 3 actionable tasks: 1 executed, 2 up-to-date
> ```

thanks for feedback.

I have clone brand andchoi_ultimateSoftwareInquiries and complie success, But when run ./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties or ./bin/single-cluster-monitor.sh --topic test --broker-list localhost:9092 --zookeeper localhost:2181 .
I seen port 8778, but I don't see port 8000. I don't know why so.
You can help  this troubleshooting thanks

**Comment by andrewchoi5** [comment]
Thanks for the update.
Looks like the index HTML file in that PR was set to something else.
Please try again with the newest commit in that PR and run the application service once you have your brokers running.

After that, try the following URL in your browser.
http://localhost:8000/index.html

![image](https://user-images.githubusercontent.com/8682887/85214719-d828c800-b323-11ea-9c2c-a0d5da21358d.png)

![image](https://user-images.githubusercontent.com/8682887/85214718-d52dd780-b323-11ea-8f31-43cf9d4e4b78.png)
![image](https://user-images.githubusercontent.com/8682887/85214720-dd861280-b323-11ea-94d0-4b4f564c12ca.png)
![image](https://user-images.githubusercontent.com/8682887/85214723-e24ac680-b323-11ea-91fe-520f5a5624cc.png)

**Comment by letran3691** [comment]
I have using PR "git clone -b andchoi_conusmerhotfix https://github.com/linkedin/kafka-monitor.git". After build success and run "./bin/single-cluster-monitor.sh --topic test --broker-list  10.10.0.12:9092 --zookeeper localhost:2181". I don't have see port 8000. I don't why, you can speak particular PR  had support graphics. Thanks

**Comment by andrewchoi5** [comment]
Hello Letran, instead of the andchoi_conusmerhotfix PR's branch (andchoi_ultimateSoftwareInquiries), could you try #269 and attempt running `clean build` as well as `./gradlew jar`?
