### ISSUE TITLE
Issue in running KafkaMonitor on Windows

### ISSUE THREAD

**Issue by shrayjai** [linkedin/kafka-monitor#297]
When i am running kafka-monitor after building,

I am getting the below error,
Error: Could not find or load main class com.linkedin.kmf.core.KafkaMonitor.

**Comment by andrewchoi5** [comment]
Thanks @shrayjai for reporting. What exact command(s) have you run that yielded the error log?

**Comment by andrewchoi5** [comment]
Also, I have created a PR that updates kafka-monitor-start.bat file with the rebranding changes.
