### ISSUE TITLE
I set topicCreationEnabled is false, it auto topic creation

### ISSUE THREAD

**Issue by brzyangg** [linkedin/kafka-monitor#300]
I set topicCreationEnabled is false, it auto topic creation
I set xinfra-monitor.properties  `topic-management.topicCreationEnabled` = false.
He still created automatically
My startup method is `./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties`

**Comment by andrewchoi5** [comment]
Hi brzyangg,

1 - Could you please include the full setup that you have when you run this? For example, include your `.properties` file, the kafka broker configs, as well as the full list of commands you run.
2 - Can you please paste the stack trace / trace logs of the Xinfra Monitor process for the duration you get the topic automatically created?

**Comment by brzyangg** [comment]
Hi andrewchoi5
I used other methods，thank you
