### ISSUE TITLE
record loss observed in consumer

### ISSUE THREAD

**Issue by dhirendraks** [linkedin/kafka-monitor#303]
sometime xinfra monitor report record loss in consumer.
inspecting the consumer service code it may occur due to record processing failure in consumer.
consumer is committing offset without passing the offset which will commit the offset returned in the last poll.
any further processing of the record sets returned in the last poll may result in error and cause consumer rebalance.
after the rebalance consumer will start processing from the new offset which will be higher than the last processed offset before the rebalance.

**Comment by andrewchoi5** [comment]
Thanks for reporting this issue!

Could you please any logs or stacktraces?
The investigation could also benefit from any examples for your scenario if you are able to share for the record loss behaviour.
