### ISSUE TITLE
There's no way to disable topic rebalancing

### ISSUE THREAD

**Issue by pikrzysztof** [linkedin/kafka-monitor#304]
Sure, there's `topic-management.rebalance.interval.ms` but that's an "int" and in milliseconds. 2^32ms is about 50 days, so not much. Can we please either change it to `long` or make it understand negative values as "never"?

**Comment by andrewchoi5** [comment]
@smccauliff does it makes sense to update `topic-management.rebalance.interval.ms` from int (in milliseconds) to 
`long` ?
