### ISSUE TITLE
Is there way to check metrics in web browser?

### ISSUE THREAD

**Issue by yhmin84** [linkedin/kafka-monitor#305]
Application version: 2.2.9

As indicated in https://github.com/linkedin/kafka-monitor/blob/master/README.md, I want to check my metrics through web browser.
I started the application with this command

```
./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties
```

and checked log messages that the application was working well.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/4729387/91291419-ff8e8c00-e7cf-11ea-919a-623037333ab9.png">

But when I tried to approach http://{my_ip}:8000/index.html, Unable to connect screen opened. When I checked LISTEN ports for the application, there was no 8000 port. 

Was I missing something? OR the README.md file is outdated?

**Comment by andrewchoi5** [comment]
Hello,

Yes, please check out https://github.com/linkedin/kafka-monitor/issues/312 for more information

**Comment by andrewchoi5** [comment]
The README will be updated accordingly
