### ISSUE TITLE
Removal of Zookeeper dependency

### ISSUE THREAD

**Issue by opsj** [linkedin/kafka-monitor#308]
With the anticipated removal of Kafka's dependency on Zookeeper via [KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum), are there any plans to remove kafka-monitor's current dependency on Zookeeper?

**Comment by andrewchoi5** [comment]
Hello opsj,

Thanks for submitting this issue!
Yes, there are plans to implement this in the next quarter (Oct~Dec of `2020 calendar` year) for the anticipated removal of `Kafka's dependency` on Zookeeper via `KIP-500`.
