### ISSUE TITLE
How to Set up a Log retention policy for the logs being generated?

### ISSUE THREAD

**Issue by revanth-itv** [linkedin/kafka-monitor#309]

**Comment by andrewchoi5** [comment]
Could you elaborate what you need?

**Comment by revanth-itv** [comment]
Hi, After setting up the Kafka monitor we noticed the `logs` directory is consuming lots of space. Since there is an option for configuring the log retention policies in Kafka to control the size and number of log files being generated i was hoping if there is something similar here too. 
Thank you for replying!

**Comment by endofcake** [comment]
This sounds like the standard retention policy that you configure on Kafka side @revanth-itv .

**Comment by andrewchoi5** [comment]
Thanks for the explanation @revanth-itv  and thanks for chiming in @endofcake! Correct, please set the configuration from the kafka side for the `standard retention policy`.
