### ISSUE TITLE
Jolokia agent configuration

### ISSUE THREAD

**Issue by kikogolk** [linkedin/kafka-monitor#312]
Hi!

I would like to know how to configure the JVM Jolokia Agent. Checking the code it seems the parameters are hardcoded I am not sure if there is any way to pass by configuration files the conf options described here: https://jolokia.org/reference/html/agents.html#agents-jvm

This is the code how the JolokiaService is created:

```java
  public JolokiaService(Map<String, Object> props, String name) throws Exception {
    _name = name;
    _jolokiaServer = new JolokiaServer(new JvmAgentConfig("host=*,port=8778"), false);
    _isRunning = new AtomicBoolean(false);
  }
```

Thanks a lot!

**Comment by andrewchoi5** [comment]
Hi kikogolk, in the past, we have removed some unneeded dependencies on Jetty. 
Jetty is only needed for the JolokiaService, but it will start its own embedded webserver should someone want to run that service. 

For more information on this commit, attempt running `git show fcb8b27e40b7f5ab77254c54ca5ee33d81b816f9` 

Sean: do we want to support Jolokia? cc: @smccauliff

**Comment by andrewchoi5** [comment]
https://github.com/linkedin/kafka-monitor/pull/315

**Comment by andrewchoi5** [comment]
README file also be updated accordingly.
