### ISSUE TITLE
Consume-service not showing any consumers

### ISSUE THREAD

**Issue by CVTJNII** [linkedin/kafka-monitor#32]
This is more a question than a bug report.  I have kafka-monitor running and it's passing messages, based on it's stats it's running as expected.  However, both kafka-manager and Burrow show the consumer list as empty.  Do the consume-service consumers not persist?

**Comment by lindong28** [comment]
Kafka Monitor doesn't not commit offset for its consumer group. It always consume from latest offset. That should be the reason why kafka-manager or burrow doesn't show the consumer group.

**Comment by CVTJNII** [comment]
Okay, thanks.  After reading about this more it seems like consumer groups are highly dependent on the client implementation, so that makes sense.
