### ISSUE TITLE
"Publish to GitHub Packages" is lying

### ISSUE THREAD

**Issue by zigarn** [linkedin/kafka-monitor#321]
https://github.com/linkedin/kafka-monitor/blob/8d8a33b9052ef6d2418f241266bf87b1f4482fb0/.github/workflows/gradle-publish.yml#L29
It doesn't publish in GitHub Packages: https://github.com/orgs/linkedin/packages?repo_name=kafka-monitor
On the other side, something is still publishing in Bintray (https://bintray.com/linkedin/maven/kafka-monitor)

Therefore, the `USERNAME` and `TOKEN` are useless for the moment.
==> https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages#example-using-gradle-groovy-for-a-single-package-in-a-repository

**Comment by andrewchoi5** [comment]
Thanks zigran, should we remove `Publish to GitHub Packages` workflow?

**Comment by zigarn** [comment]
I don't know, if the goal is to publish in GitHub packages, then better to make it work.
