### ISSUE TITLE
Support for Schema Registry

### ISSUE THREAD

**Issue by endofcake** [linkedin/kafka-monitor#322]
Is there a way to configure xinfra-monitor to exercise Schema Registry? I looked at the configurations for producer and consumer, but it doesn't look straightforward.
Thanks.

**Comment by andrewchoi5** [comment]
cc: @sudoa

**Comment by sudoa** [comment]
Hi @endofcake, could you elaborate a bit on "exercise schema registry" use case?

**Comment by endofcake** [comment]
@sudoa , sure. The basic idea is that if the producer and the consumer exercise Schema Registry as they produce and consume, this would give us better coverage for our end-to-end testing. In real world, is something were to happen to our Schema Registry, the users would experience an outage even though Kafka itself may be fine, so we'd want to cover this use case.
