### ISSUE TITLE
ERROR when running xinfra-monitor Linux

### ISSUE THREAD

**Issue by Hbensaadi** [linkedin/kafka-monitor#329]
Hello i'm running xinfra-monitor with kakfa cluster on ubuntu.
When i'm  executing  the following commande 
`./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties`
I get the bellow error:

`Error: Could not find or load main class com.linkedin.xinfra.monitor.XinfraMonitor
Caused by: java.lang.ClassNotFoundException: com.linkedin.xinfra.monitor.XinfraMonitor`

Any idea about this issue?

**Comment by JavesonYehudi** [comment]
How did you solve it? I'm currently facing the same issue.
