### ISSUE TITLE
the properties file name is misspelt, kafak-monitor.properties this should be kafka-monitor.properties

### ISSUE THREAD

**Issue by kami619** [linkedin/kafka-monitor#57]
Configuration Tips

We advise advanced users to run Kafka Monitor with ./bin/kafka-monitor-start.sh config/kafka-monitor.properties. The default **kafak-monitor.properties** in the repo provides an simple example of how to monitor a single cluster. You probably need to change the value of zookeeper.connect and bootstrap.servers to point to your cluster.

**Comment by WarrenGreen** [comment]
Thanks @kami619 - Fixing that now.
