### ISSUE TITLE
kafka-monitor jdk7 compile error

### ISSUE THREAD

**Issue by powerLambda** [linkedin/kafka-monitor#7]
According the the project README and build it with JDK7 failed, it looks like some JDK8 syntax is used.
The README is misleading, shall we update it?

Kafka Monitor requires Gradle 2.0 or higher. 

> Java 7 should be used for building in order to support both Java 7 and Java 8 at runtime.

/opt/Development/github_repo/kafka-monitor/services/src/main/java/com/linkedin/kmf/services/ProduceService.java:176: error: ')' expected
        (config, now) -> {
               ^

**Comment by lindong28** [comment]
@powerLambda Sorry for late reply. Just notice the issues.

I will update the code so that it works with Java 7. Thanks for noting this!

**Comment by lindong28** [comment]
@powerLambda  I have updated the README to note that only Java 8 is supported at this moment. Thanks again for your notice.

**Comment by lindong28** [comment]
@powerLambda I have updated the code so that it is compatible with Java 1.7 now. Please let me know if there is still problem. Thanks!
