### ISSUE TITLE
publish on docker hub?

### ISSUE THREAD

**Issue by simplesteph** [linkedin/kafka-monitor#71]
Is it possible to get a working image published on docker hub? Tried building one myself, had to modify the Dockerfile at `docker/Dockerfile`, the logic works (consumer / producer), but the UI and jolokia are not accessible. Would be great to get something to plug and play readily available.

**Comment by smccauliff** [comment]
We don't use docker at LinkedIn.  The existing dockerfile was contributed to the project.  If you get something working you believe would be useful please contribute it.
