### ISSUE TITLE
Connecting to Kafka over SSL/TLS

### ISSUE THREAD

**Issue by SecurityInsanity** [linkedin/kafka-monitor#78]
Does kafka-monitor support connecting over an SSL Listener in Kafka?
I'd like to not have to open a plaintext listener for just kafka-monitor.

If so is what does the configuration look like? Searching for "SSL"/"TLS" didn't bring up much in issues/prs/the wiki.

**Comment by smccauliff** [comment]
You should be able to pass in the kafka security configs where the producer and consumer are configured.  For example:

security.protocol=SSL
ssl.truststore.location=/var/private/ssl/kafka.client.truststore.jks
ssl.truststore.password=test1234
ssl.keystore.location=/var/private/ssl/kafka.client.keystore.jks
ssl.keystore.password=test1234
ssl.key.password=test1234

https://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption/

**Comment by SecurityInsanity** [comment]
Ah Yep. It appears I was looking at Kafka-Monitor as doing something else, and it lead to the confusion.

Thanks
