### ISSUE TITLE
Open  192.168.89.2:8000/index.html  ERROR 404

### ISSUE THREAD

**Issue by zqc0512** [linkedin/kafka-monitor#81]
when changekafka-monitor.properties and run kafka-monitor-start.sh config/kafka-monitor.properties
I open ip:8000/index.html  out put ERROR 404 thanks.
@lindong28

**Comment by lindong28** [comment]
@zqc0512 Would it work if you use localhost:8000/index.html? Also https://github.com/linkedin/kafka-monitor/issues/9 may help if you are running it on docker.

**Comment by zqc0512** [comment]
i restart it and can see in chrome.can close it.
thanks. 
@lindong28
