### ISSUE TITLE
Gradle build failed - can't access the Maven project object model (POM) artifacts

### ISSUE THREAD

**Issue by ibm4mb** [linkedin/kafka-monitor#86]
I wonder if the URLs are hard-coded in the java programs that access 

exec /opt/jdk1.8.0_131/bin/java -Dorg.gradle.appname=gradlew -classpath /opt/linkedin/kafka-monitor-master/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain jar
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve net.sourceforge.argparse4j:argparse4j:0.5.0.
  Required by:
      project :
   > Could not resolve net.sourceforge.argparse4j:argparse4j:0.5.0.
      > Could not get resource 'https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.5.0/argparse4j-0.5.0.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.5.0/argparse4j-0.5.0.pom'.
            > repo1.maven.org: Name or service not known
> Could not resolve org.slf4j:slf4j-log4j12:1.7.6.
  Required by:
      project :
   > Could not resolve org.slf4j:slf4j-log4j12:1.7.6.
      > Could not get resource 'https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.pom'.
            > repo1.maven.org
> Could not resolve org.apache.avro:avro:1.4.0.
  Required by:
      project :
   > Could not resolve org.apache.avro:avro:1.4.0.
      > Could not get resource 'https://repo1.maven.org/maven2/org/apache/avro/avro/1.4.0/avro-1.4.0.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/apache/avro/avro/1.4.0/avro-1.4.0.pom'.
            > repo1.maven.org
> Could not resolve org.apache.kafka:kafka_2.11:0.10.1.1.
  Required by:
      project :
   > Could not resolve org.apache.kafka:kafka_2.11:0.10.1.1.
      > Could not get resource 'https://repo1.maven.org/maven2/org/apache/kafka/kafka_2.11/0.10.1.1/kafka_2.11-0.10.1.1.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/apache/kafka/kafka_2.11/0.10.1.1/kafka_2.11-0.10.1.1.pom'.
            > repo1.maven.org
> Could not resolve org.apache.kafka:kafka-clients:0.10.1.1.
  Required by:
      project :
   > Could not resolve org.apache.kafka:kafka-clients:0.10.1.1.
      > Could not get resource 'https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/0.10.1.1/kafka-clients-0.10.1.1.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/0.10.1.1/kafka-clients-0.10.1.1.pom'.
            > repo1.maven.org
> Could not resolve org.testng:testng:6.8.8.
  Required by:
      project :
   > Could not resolve org.testng:testng:6.8.8.
      > Could not get resource 'https://repo1.maven.org/maven2/org/testng/testng/6.8.8/testng-6.8.8.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/testng/testng/6.8.8/testng-6.8.8.pom'.
            > repo1.maven.org
> Could not resolve org.eclipse.jetty:jetty-server:8.1.19.v20160209.
  Required by:
      project :
   > Could not resolve org.eclipse.jetty:jetty-server:8.1.19.v20160209.
      > Could not get resource 'https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/8.1.19.v20160209/jetty-server-8.1.19.v20160209.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/8.1.19.v20160209/jetty-server-8.1.19.v20160209.pom'.
            > repo1.maven.org
> Could not resolve org.json:json:20140107.
  Required by:
      project :
   > Could not resolve org.json:json:20140107.
      > Could not get resource 'https://repo1.maven.org/maven2/org/json/json/20140107/json-20140107.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/json/json/20140107/json-20140107.pom'.
            > repo1.maven.org
> Could not resolve com.fasterxml.jackson.core:jackson-databind:2.7.1.
  Required by:
      project :
   > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.7.1.
      > Could not get resource 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.1/jackson-databind-2.7.1.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.7.1/jackson-databind-2.7.1.pom'.
            > repo1.maven.org
> Could not resolve org.jolokia:jolokia-jvm:1.3.3.
  Required by:
      project :
   > Could not resolve org.jolokia:jolokia-jvm:1.3.3.
      > Could not get resource 'https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.3.3/jolokia-jvm-1.3.3.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.3.3/jolokia-jvm-1.3.3.pom'.
            > repo1.maven.org
> Could not resolve net.savantly:graphite-client:1.1.0-RELEASE.
  Required by:
      project :
   > Could not resolve net.savantly:graphite-client:1.1.0-RELEASE.
      > Could not get resource 'https://repo1.maven.org/maven2/net/savantly/graphite-client/1.1.0-RELEASE/graphite-client-1.1.0-RELEASE.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/net/savantly/graphite-client/1.1.0-RELEASE/graphite-client-1.1.0-RELEASE.pom'.
            > repo1.maven.org
> Could not resolve com.timgroup:java-statsd-client:3.0.1.
  Required by:
      project :
   > Could not resolve com.timgroup:java-statsd-client:3.0.1.
      > Could not get resource 'https://repo1.maven.org/maven2/com/timgroup/java-statsd-client/3.0.1/java-statsd-client-3.0.1.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/com/timgroup/java-statsd-client/3.0.1/java-statsd-client-3.0.1.pom'.
            > repo1.maven.org

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by ibm4mb** [comment]
Tried the --offline option, after dropping the jars in various libraries. No luck.

00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not resolve all dependencies for configuration ':compileClasspath'.
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve net.sourceforge.argparse4j:argparse4j:0.5.0.
00:41:21.915 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of net.sourceforge.argparse4j:argparse4j:0.5.0 available for offline mode.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.slf4j:slf4j-log4j12:1.7.6.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of org.slf4j:slf4j-log4j12:1.7.6 available for offline mode.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.apache.avro:avro:1.4.0.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of org.apache.avro:avro:1.4.0 available for offline mode.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.apache.kafka:kafka_2.11:0.10.1.1.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of org.apache.kafka:kafka_2.11:0.10.1.1 available for offline mode.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.apache.kafka:kafka-clients:0.10.1.1.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of org.apache.kafka:kafka-clients:0.10.1.1 available for offline mode.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve org.testng:testng:6.8.8.
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :
00:41:21.916 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > No cached version of org.testng:testng:6.8.8 available for offline mode.

**Comment by lindong28** [comment]
@ibm4mb Are you building kafka-monitor on a machine with network access to maven repository? It seems that gradle is not able to fetch the jar from maven repository. In order to understand whether this is kafka-monitor's issue or the network connection issue, can you try compile Apache Kafka using gradle?

**Comment by ibm4mb** [comment]
Thank you, so much for responding. I was able execute the Gradle build on on my windows personal computer. But wanted to execute an offline Gradle build on a Red Hat Enterprise Linux 7.x Virtual Machine, and wrestled with build after downloading the JARs that the build was complaining. If you can kindly share any documents or wikis that instruct how to build the kafka-monitor that'd be fantastic. Thanks in advance.

**Comment by lindong28** [comment]
@ibm4mb Sure thing. I am happy to help :)

We have tested kafka-monitor compilation and it should work with `./gradlew jar`, as you can see in the README at https://github.com/linkedin/kafka-monitor. All quick-start instructions, including the steps to build kafka-monitor, are put in this README.

Thus it seems that you are observing these errors because you tried to build kafka-monitor as an offline Gradle build on a virtual machine. We haven't tested kafka-monitor in such an environment so I am not sure whether it is expected to work. But it seems to me that it should work in the same way as any other gradle-based project such as Apache Kafka. Therefore, I am wondering if you are able to build Apache Kafka or any other open source gradle-based project as offline Gradle build on that virtual machine. Can you try that?

**Comment by ibm4mb** [comment]
@lindong28, yes you're right. The problem is with executing a successful offline Gradle build, on a VM, because the build process tries to access the JARs locally (not sure which directory). So the process stops when it can't find the dependencies. 

First time around, the online Gradle build stopped when my machine couldn't access the 3rd party JARs such as the Maven repositories on the internet.

Ideally it would be nice to have instructions to do an offline build for using a Kafka cluster within the intranet. 

Thank you
