### ISSUE TITLE
Email notifications on certain events

### ISSUE THREAD

**Issue by ajnarayan** [linkedin/kafka-monitor#90]
Is there a possibility of having the monitor send email when certain events occur?

Example scenario would be to send an email when produce-availability-avg < 0.5

**Comment by lindong28** [comment]
@ajnarayan This feature is currently not supported. But the current design of kafka-monitor makes it easy to be extended to support this. For example, you can have your own service that periodically polls interested metric values (e.g. message loss rate, availability) and trigger event if some rules are satisfied. This can be implemented similar to how `DefaultMetricsReporterService` is implemented. It only requires a new Service class and no existing code needs to be changes.

I think implementation of this feature is easy. The hard part is the design of the interface, i.e. how should we allow user to specify the rules and actions that achieve a proper balance between expressiveness and ease-of-use.

I am not sure we will implement this feature at LinkedIn in the near future given that we don't need this feature. At LinkedIn we have another service which pull metrics and generate email alert. But you are free to implement your own service that does this. We can also merge your patch if it is good for most users.
