### ISSUE TITLE
Adding tests in kafka-monitor.properties

### ISSUE THREAD

**Issue by Rishi8991** [linkedin/kafka-monitor#96]
Hello,

I am a little confused on how exactly to add tests in the kafka-monitor.properties file. For example, how would I add the test to see if MirrorMaker is working? 

Furthermore, is there functionality to notify a user when a particular service like zookeeper is not running or crashed?

**Comment by lindong28** [comment]
@Rishi8991 Sorry for late reply..

You can monitor MirrorMaker by modifying `config/multi-cluster-monitor.properties`. All you need is to change the `zookeeper.connect` and `bootstrap.servers` as appropriate to point to source and destination clusters.
