### ISSUE TITLE
setup sasl_ssl authentication

### ISSUE THREAD

**Issue by shaikshakeel** [linkedin/kafka-monitor#99]
Hi, 

How can I setup sasl_ssl authentication in Kafka-monitor?

where can I set and how?

**Comment by lindong28** [comment]
Hey @shaikshakeel, yes you should be able to use the sasl_ssl in Kafka Monitor in the same way as  you would do with Apache Kafka. For example, you can find documentation of Apache Kafka producer configs at https://kafka.apache.org/documentation/#producerconfigs. You can specify these configs in the map `produce.producer.props` in the file `config/kafka-monitor.properties` and run `./bin/kafka-monitor-start.sh config/kafka-monitor.properties`.
